### ISSUE TITLE
'Over-Sensitive' SelectView

### ISSUE THREAD

**Issue by PenguinMan98** [sproutcore/sproutcore#1353]
The issue is that if you click quickly to open a selectView, sometimes it chooses an option for you and immediately closes again.

Here are a few example screencaptures:
Edge in Win 10: http://screencast.com/t/YpUTLg7ZFln
Safari in OSX: http://screencast.com/t/9xQ0xR4g

**Comment by mauritslamers** [comment]
As mentioned on Gitter, my hunch is that something goes wrong in the state management of the select view, perhaps a mouse up event which is consumed by the wrong view. Consequently, the state of the select is corrupt, and the next mouse up event on the select view causes an immediate selection action instead of an open-the-menu action.

**Comment by nicolasbadia** [comment]
Before going deeper into this, I suggest that we merge the experimental select view. 
I have a PR for this https://github.com/sproutcore/sproutcore/pull/1259. I can take care to merge it and fix the conflicts if it's ok for you.

**Comment by mirion** [comment]
I'm using a development version of nicolasbadia's experimental SelectView and I'm very happy with it. 

I'm not aware of any compatibility issues, but in case of doubt, we can merge it as "experimental", advertise its availability and get some feedback before promoting it as the default version.

**Comment by nicolasbadia** [comment]
I believe this is not an issue in the new SC.SelectView. reopen if it is not the case.
